# Load R image
image:
  file: .gitpod.Dockerfile

# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
# Init runs during prebuild.
tasks:
  - name: Setup
    init: > # In YAML, > introduces spaces while | introduces newlines. XML libs required to build XML properly?
      Rscript -e '
        r = getOption("repos"); r["CRAN"]="http://cran.us.r-project.org"; options(repos=r);
        install.packages("remotes");
        remotes::install_github("ucl-medical-genomics/matt")
      '
    command: echo 'Run R setup'

# Settings
vscode:
  extensions:
    - Ikuyadeu.r
  
# # List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
# ports:
#   - port: 3000
#     onOpen: open-preview

