# Load R image
image:
  file: .gitpod.Dockerfile

# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - name: Setup
    init: > # In YAML, > introduces spaces while | introduces newlines.
      Rscript -e 'install.packages("remotes")'
      -e 'remotes::install_github("ucl-medical-genomics/matt")' # runs during prebuild
    command: echo 'Run R setup'

# Settings
vscode:
  extensions:
    - Ikuyadeu.r@1.2.1:z5vr1v1bfS++U/aHLSXQ6Q==

# # List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
# ports:
#   - port: 3000
#     onOpen: open-preview

